dbus2/zbus

zbus/src/blocking/connection.rs
zbus/src/connection.rs

Most likely, querying the group IDs will involve potentially blocking calls (e.g `getgrouplist` is blocking on Linux) so best be safe and keep it async from the get go so we don't have to break API.
---

zb: Connection::peer_credentials now async

---

zbus/src/message.rs
zbus/src/message_header.rs
zvariant/src/container_depths.rs
zvariant/src/dbus/de.rs
zvariant/src/signature_parser.rs

This is to address some issues spotted during recent fuzzing runs in the CI:
https://github.com/dbus2/zbus-old/actions/runs/4915689965/jobs/8778478660
https://github.com/dbus2/zbus-old/actions/runs/4927346573/jobs/8804199850

zv,zb: Add missing container depth checks + Reject empty structs in signatures

---

zvariant/src/lib.rs
zvariant/src/optional.rs

Otherwise we end up with a infinite mutual recursion between these calls and hence a stack overflow.
Fixes #343.

zv: Optional::default shouldn't call NoneValue::null_value

---

zvariant/src/framing_offset_size.rs
zvariant/src/lib.rs

Fix gvariant offsets on 32-bit systems + fix gvariant tests on big endian hosts

---

zbus/src/message_builder.rs
zbus/src/message_fields.rs

These fields are dependent on the body and that's specified later.
---

🚑️ zb: Drop signature & fds from fields in MessageHeader -> MessageBuilder conversion

---

zbus/src/fdo.rs

For non-Copy fields (i-e those requiring allocation).
---

✨ zb: Owned getters for ConnectionCredentials fields

---

zbus/src/guid.rs

So that this can be returned from `dbus_interface` and `dbus_proxy` methods.
---

✨ zb: Implement Type, Serialize & Deserialize for `Guid`

---

zbus/src/match_rule.rs

🐛 zb: Don't choke on empty match rule arg values

---

book/src/faq.md

The property caching feature wasn't well documented. This commit adds it to the FAQ section of the book.

Adding disable property caching FAQ

---

zbus/src/message.rs

✨ zb: Add a from_bytes constructor for Message 

---

zbus/src/match_rule.rs
zbus/src/match_rule_builder.rs

arg0namespace has an overly restrictive type (InterfaceName), which disallows valid values (e.g. those containing '-' or single-element names such as 'org').
Further more, a MatchRule with arg0namespace previously would not match a message whose arg0 is not a valid InterfaceName (even if it is a valid BusName).
fixes #382

zb: add arg0ns to match rule, deprecate arg0namespace

---

zvariant/src/type.rs

✨ zv: Implement Type for std::collections::HashSet

---

zbus/src/fdo.rs

This proxy was obviously added in a hurry, w/o much thought given but we also didn't have the `MatchRule` type then to use.
Since 2 commits here are breaking API, I will contact the [only](https://github.com/azymohliad/watchmate/blob/3fb3fa89fc76a783f46abdc5f07e9a59ed23ac1f/infinitime/src/freedesktop/notifications.rs#L32) [2](https://github.com/tau-OS/kiri-desktop/blob/97b86e48731e30ba14572b16aec864cdbfa0a171/d5/src/notify.rs#L102) users of this API I could find on Github and see if they'd mind us breaking API for this.

Monitoring proxy improvements

---

zvariant/src/array.rs
zvariant/src/dict.rs
zvariant/src/maybe.rs
zvariant/src/structure.rs
zvariant/src/value.rs

Closes #366
~~Marked as a draft since bytestring and str Display implementations are currently broken on edge cases.~~

✨ zv: impl Display for Value, Array, Structure, Dict & Maybe

---

zbus/src/fdo.rs

The object path defaults to be based on the interface name otherwise and that's not the expected bhaviour.
---

🚸 zb: Specify object path for Monitoring & Debug.Stats proxies

---

zbus/src/abstractions/executor.rs
zbus/src/object_server.rs
zbus/tests/e2e.rs

A wrapper interface method response type that notifies the caller of the response being sent off.

🏷️ zb: Add ResponseDispatchNotifier type

---

zbus/src/message_field.rs
zvariant/src/from_value.rs
zvariant/src/signature.rs
zvariant/src/structure.rs
zvariant/src/type.rs
zvariant/src/value.rs

This PR implements `Signature::as_ref()` to get a borrowed clone of a `Signature`. The code is a copy of `Str::as_ref()`.
Even though cloning an `Arc` is cheap, it's not exactly for free. An atomic increment has some inherent overhead, and `Arc::clone()` also `panic!()`s if there are excessively many strong references to an `Arc`. For every `panic!()` some code to unwind the stack has to be generated, which hurts cache locality, and bloats the generated code.

⚡  zvariant, zbus: use borrowed clone if possible

---

zbus/Cargo.toml
zbus/src/match_rule/mod.rs
zbus_macros/Cargo.toml
zbus_macros/src/iface.rs
zbus_macros/src/proxy.rs
zbus_names/Cargo.toml
zbus_names/src/bus_name.rs
zbus_names/src/error_name.rs
zbus_names/src/interface_name.rs
zbus_names/src/member_name.rs
zbus_names/src/unique_name.rs
zbus_names/src/well_known_name.rs
zbus_polkit/Cargo.toml
zbus_xmlgen/Cargo.toml
zvariant/Cargo.toml
zvariant/fuzz/Cargo.toml
zvariant/src/dbus/de.rs
zvariant/src/dbus/ser.rs
zvariant/src/de.rs
zvariant/src/gvariant/de.rs
zvariant/src/gvariant/ser.rs
zvariant/src/lib.rs
zvariant/src/object_path.rs
zvariant/src/ser.rs
zvariant/src/signature.rs
zvariant/src/value.rs
zvariant_derive/Cargo.toml
zvariant_derive/src/lib.rs
zvariant_utils/Cargo.toml

So that people can pass strings directly and let us worry about conversion to a `Signature` instance.
This involves changing some public methods to return a Result but they are rarely used directly.

🚸 zv: Make signature parameter generic

---

zbus/src/connection/mod.rs
zbus/src/error.rs
zbus/src/fdo.rs
zbus/src/match_rule/builder.rs
zbus/src/match_rule/mod.rs
zvariant/src/error.rs
zvariant/src/lib.rs
zvariant_derive/src/dict.rs
zvariant_derive/src/lib.rs

Time to drop deprecated APIs, excluding the new aliases/re-exports.

Drop deprecated APIs

---

zbus/src/message/builder.rs
zbus/src/message/header.rs
zbus/src/message/mod.rs
zvariant/README.md
zvariant/benches/benchmarks.rs
zvariant/fuzz/fuzz_targets/utils.rs
zvariant/src/de.rs
zvariant/src/deserialize_value.rs
zvariant/src/encoding_context.rs
zvariant/src/lib.rs
zvariant/src/optional.rs
zvariant/src/owned_value.rs
zvariant/src/ser.rs
zvariant/src/value.rs
zvariant_derive/README.md
zvariant_derive/src/lib.rs
zvariant_derive/tests/tests.rs

The deserializer is driven by the signature and it could happen that not all bytes are consumed from the input slice and this could be useful information for the caller.

✨ zv: from_slice now also return number of bytes parsed

---

.github/workflows/rust.yml

This reverts commit a78532eee6ffd628c2095e4bcde3a0e9970cb13c.
Seems this commit broke the CI on Windows:
https://github.com/dbus2/zbus/actions/runs/5763515467/job/15625520852?pr=428
---

Revert "👷 GH,CI: update the win32 path list to cache"

---

CONTRIBUTING.md

Please feel free to squash these together, I have no preferences here.

CONTRIBUTING: fix a few typos and a minor rewording

---

zbus/src/blocking/proxy/mod.rs
zbus/src/proxy/mod.rs
zbus_macros/src/proxy.rs

This PR fixes #433 by adding a `ProxyImpl` trait for macro generated proxy-structs to allow narrowing generic arguments to D-Bus proxies.

✨ zb: add ProxyImpl trait

---

book/src/server.md
zbus/src/connection/mod.rs
zbus/src/error.rs
zbus/src/fdo.rs
zbus/src/lib.rs
zbus/src/match_rule/mod.rs
zbus/src/message/builder.rs
zbus/src/message/field.rs
zbus/src/message/fields.rs
zbus/src/message/header.rs
zbus/src/message/mod.rs
zbus/src/object_server/interface.rs
zbus/src/object_server/mod.rs
zbus/src/proxy/mod.rs
zbus/tests/e2e.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/src/proxy.rs

Many improvements to message module API, improving the ergonomics and performance.
Among other things, it drops/hides a lot of low-level API that IMO we should have never provided. In my defense, I was new to Rust when I wrote this code. :)
---

🔥 message mod API improvements

---

zbus_names/src/bus_name.rs
zbus_names/src/error_name.rs
zbus_names/src/interface_name.rs
zbus_names/src/member_name.rs
zbus_names/src/unique_name.rs
zbus_names/src/well_known_name.rs
zvariant/src/str.rs

This PR reduces Debug impls verbosity but retains possibly useful information.
See also https://github.com/dbus2/zbus/pull/394 
Before:
```
Str::from_static("hello") = Str(
Static(
"hello",
),
)
Str::from("hello") = Str(
Borrowed(
"hello",
),
)
Str::from(String::from("hello")) = Str(
Owned(
"hello",
),
)
UniqueName::from_static_str_unchecked(":1.2") = UniqueName(
Str(
Static(
":1.2",
),
),
)
OwnedUniqueName::from(UniqueName::from_static_str_unchecked(":1.2")) = OwnedUniqueName(
UniqueName(
Str(
Static(
":1.2",
),
),
),
)
WellKnownName::from_static_str_unchecked("org.gnome.Console") = WellKnownName(
Str(
Static(
"org.gnome.Console",
),
),
)
OwnedWellKnownName::from(WellKnownName::from_static_str_unchecked("org.gnome.Console")) = OwnedWellKnownName(
WellKnownName(
Str(
Static( …
```

🧑‍💻 zv, zn: Improve Str, Owned*Name, BusName Debug impls

---

book/src/blocking.md
book/src/connection.md
zbus/src/abstractions/async_lock.rs
zbus/src/blocking/connection/mod.rs
zbus/src/connection/builder.rs
zbus/src/connection/handshake.rs
zbus/src/connection/mod.rs
zbus/src/connection/raw/connection.rs
zbus/src/connection/raw/mod.rs
zbus/src/connection/raw/socket.rs
zbus/src/connection/socket_reader.rs

The main change in this PR, is to rework `Socket` trait to be more high-level and provide async API. Dropping of `futures::Sink` made way for this but there are also other reasons we are probably better off without it (see the relevant commit log) until and unless this trait is improved upstream.
---

💥 zb: Improved Socket trait + drop Sink implementation

---

.github/workflows/rust.yml

We've been bitten by this before (#330) so let's check for this in the CI.
---

👷 CI: Enable pedantic clippy large futures warning

---

zbus/src/fdo.rs

According to the spec:
> An empty string may be provided for the interface name; in this case, if
> there are multiple properties on an object with the same name, the
> results are undefined (picking one by according to an arbitrary
> deterministic rule, or returning an error, are the reasonable
> possibilities).
Fixes #302.
---

💥 zb: Optional interface on fdo::PropertiesProxy::get_all

---

zbus/src/connection/mod.rs
zbus/src/fdo.rs
zbus/src/lib.rs
zbus/src/message/builder.rs
zbus/src/message/mod.rs
zbus/tests/e2e.rs
zbus_macros/tests/tests.rs

Not only this makes sense anyway, it also makes the method much simpler as we can drop the optional arguments and therefore also the need for user to have to specify the concrete types for these arguments even when they just want to pass `None`.

🚸 Message constructor to return a builder instance

---

.github/workflows/rust.yml
zbus/Cargo.toml
zbus_macros/Cargo.toml
zbus_names/Cargo.toml
zbus_xml/Cargo.toml
zbus_xmlgen/Cargo.toml
zvariant/Cargo.toml
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml

Seems one of our indirect dependencies, `toml_edit` has bumped to this and since Rust 1.66 was released more than 9 months ago, it's not that big a deal.
---

⬆️  Bump MSRV to 1.66

---

book/src/client.md

Updates the outdated GDBus URL,which currently leads to the GIO homepage.

book: update outdated URL

---

book/src/faq.md
zbus/Cargo.toml
zbus/tests/e2e.rs
zvariant/Cargo.toml
zvariant/README.md
zvariant/src/container_depths.rs
zvariant/src/dbus/de.rs
zvariant/src/dbus/ser.rs
zvariant/src/gvariant/de.rs
zvariant/src/gvariant/ser.rs
zvariant/src/into_value.rs
zvariant/src/lib.rs
zvariant/src/maybe.rs
zvariant/src/type.rs
zvariant/src/value.rs

Add a non-default feature, `option-as-array` that enables this. Also, add a FAQ item to the book, explaining how people can handle nullable types.
---

Allow ser/de of `Option<T>` as array

---

zvariant/src/signature.rs

This adjusts the `PartialEq` impls to evaluate equality irrespective of
of marshalling of the type.
Two signatures representing the same type can differ as a result of
D-Bus marshalling. D-Bus marshalling will omit outer parentheses from body
singatures.
Consider a `MyType { a: i32, b: i32}`:
`MyType::signature()` returns a "(ii)" `Signature` whereas
`Message::body_signature()` with `MyType` as body, would return
a "ii" `Signature`, which may lead to unexpected inequality of `Signature`s.
Note: `PartialEq` on `Signature` accounts for marshalling only.
One can construct- or deserialize into deeper nested structs or tuples than
than the signature describes but at that point the divergence is expected.

🩹 🚸 zv: Equal `Signature`s irrespective of D-Bus marshalled state

---

zbus/Cargo.toml
zbus/src/connection/socket/unix.rs
zbus_xml/Cargo.toml
zvariant/Cargo.toml

Only syn and event-listener are still outdated, as they required quite some more work to fix. Plus syn is already handled in #404.

Bump most dependencies

---

.github/workflows/deploy.yml
.github/workflows/release.yml
.github/workflows/rust.yml

This reverts commit 7e486f5817c76cd98a7b89565662f89f7d5cf24b.
The cost is very high. Let's just stick to the default runners for now.

Revert "👷 CI: Use large runners for faster actions"

---

zbus_names/src/bus_name.rs
zbus_names/src/error_name.rs
zbus_names/src/interface_name.rs
zbus_names/src/member_name.rs
zbus_names/src/unique_name.rs
zbus_names/src/utils.rs
zbus_names/src/well_known_name.rs
zvariant/src/object_path.rs
zvariant/src/signature.rs

Similar to `String` is `Basic`, `OwnedObjectPath` should also be `Basic`. 
This allows to convert `OwnedValue` into `HashMap` with `OwnedObjectPath` key type.

zv,zn: impl `Basic` for applicable types

---

zvariant/src/array.rs
zvariant/src/dict.rs
zvariant/src/fd.rs
zvariant/src/lib.rs
zvariant/src/maybe.rs
zvariant/src/object_path.rs
zvariant/src/signature.rs
zvariant/src/structure.rs
zvariant/src/value.rs

adds a test to assert the desired behavior described in #484.
Credits to @sivizius for reviewing and contributing.
closes #484

zv: store entries of Dict as BTreeSet to keep it ordered

---

zbus_xmlgen/src/lib.rs
zbus_xmlgen/tests/data/sample_object0.rs
zbus_xmlgen/tests/data/sample_object0.xml

Fixes: #257 
When the xml signature had a nested element (such as a nested dict), the parser wasn't cleaning up the closing character after peeking the iterator. Fixed by consuming the next iterator before proceeding.

🐛 zbus_xmlgen: Fix nested signature parser

---

zbus/src/lib.rs
zvariant/src/array.rs
zvariant/src/dict.rs
zvariant/src/from_value.rs
zvariant/src/lib.rs
zvariant/src/maybe.rs
zvariant/src/signature.rs
zvariant/src/str.rs
zvariant/src/value.rs
zvariant_derive/src/value.rs

Fix Value & related API and make them more consistent

---

zbus_xmlgen/src/lib.rs
zbus_xmlgen/tests/data/sample_object0.rs
zbus_xmlgen/tests/data/sample_object0.xml

When the xml element had a struct containing only a single type, the parser was returning the element itself. This was wrong since a D-Bus struct is expected to be translated into a tuple, regardless of how many types it has (except for 0 elements, which is not accepted according to D-Bus spec). Returning a single-element tuple type instead.
Note: As defined on Rust syntax, the single-element tuple type has a trailing comma inside parenthesis, not to be confused with compiler lint "unused_parens". Examples:
(i32,) --> OK. Single-element tuple with i32 element. (i32) --> ERROR. Wrong use of parenthesis that clutters readability.
About the change itself on _zbus_xmlgen/src/lib.rs_, it was noticed that we could somewhat simplify by removing the else-if condition and doing it all in the same …

bug zbus_xmlgen: Fix structs with a single element

---

zbus_xmlgen/src/lib.rs
zbus_xmlgen/tests/data/sample_object0.rs
zbus_xmlgen/tests/data/sample_object0.xml

This hides the [`clippy::too_many_arguments`](https://rust-lang.github.io/rust-clippy/master/index.html#/too_many_arguments) and [`clippy::type_complexity`](https://rust-lang.github.io/rust-clippy/master/index.html#/type_complexity) lints for generated functions.
Note that type complexity is only an estimate, so future adjustments may be necessary. I tested it with the interface files for [`org.freedesktop.UDisks2.xml`](https://github.com/storaged-project/udisks/blob/a76eda89a4c747f12dc05670f376d95d8ec4cd45/data/org.freedesktop.UDisks2.xml) and confirmed that it is working correctly.
Closes https://github.com/dbus2/zbus/issues/512.

✨ zx: hide clippy lints for generated functions

---

book/src/client.md
zbus/examples/watch-systemd-jobs.rs

I'm unfamiliar with both D-Bus and Rust. I found the current signals example in the zbus book, which uses GeoClue, too complicated for getting started. So I figured I would contribute a simpler one.
The example monitors for new systemd services starting (interface `org.freedesktop.systemd1.Manager` signal `JobNew`).
I also added it as `zbus/examples/watch-systemd-jobs.rs` so it can be executed with `cargo run --example watch-systemd-jobs`.
Also updated the `Stream` trait link to point to latest `futures` library version.

:memo: book: Add a simpler D-Bus signals example 

---

zbus/tests/e2e.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/src/proxy.rs
zbus_macros/src/utils.rs
zbus_macros/tests/tests.rs

Implements  #323: enables interface property macros on getters to be annotated with `emits_changed_signal`.

#323 enable `emits_changed_signal` on `dbus_interface`

---

book/src/blocking.md
book/src/server.md
zbus/Cargo.toml
zbus/src/address.rs
zbus/src/blocking/connection/mod.rs
zbus/src/blocking/object_server.rs
zbus/src/connection/mod.rs
zbus/src/connection/socket_reader.rs
zbus/src/object_server/mod.rs
zbus/src/proxy/mod.rs
zbus/tests/e2e.rs

Slight modification of #494 , fixes #479 
Depends on getting [rust_uds_windows/#9](https://github.com/haraldh/rust_uds_windows/pull/9) merged upstream.
For now I have added my person Github entry as the location for `uds_windows`. This should let us test of the tests pass now.
Once I get this merged upstream, I'll commit, squash, add emojis, etc. here.

Actual smol rs update

---

zbus/Cargo.toml
zbus/src/win32.rs

This pull request migrates to [`windows-sys`](https://crates.io/crates/windows-sys) from [`winapi`](https://crates.io/crates/winapi). All tests pass.
Resolves #534

⬆️ Migrate to windows-sys from winapi (#534)

---

zbus/src/blocking/connection/mod.rs
zbus/src/connection/mod.rs

The `event-listener` crate will be breaking API again soon so it's best to abstract away the small part that we expose to the user. This will allow us to update to the new API without breaking our own API.

🚸 zb: Connection::monitor_activity now returns Activity type

---

.github/workflows/rust.yml
zbus/src/win32.rs

We're using options that are only available in nightly.

👷 CI: Run lint job against nightly

---

.github/workflows/rust.yml
zbus/Cargo.toml
zvariant/src/fd.rs

This mainly removes accidental enabling of the tokio feature in one of the `cargo test` runs. This likely means that we've been running most of the tests on Linux with tokio-only for a long time now (since 3.0 probably). This PR aims to fix that.
Some other fixes and a workaround also included.

Fix tokio testing

---

zbus/src/guid.rs

Connection::new_unix_server no longer exists, so I've replaced it with the appropriate current method.
---
There's also a reference to this method in book-1.0, but I wasn't sure whether that should be updated.

📝 zb: update documentation for Guid::generate

---

.github/workflows/rust.yml

We currently don't have any tests that actually create a vsock socket but at least this tests the build and address parsing tests. Later if/when we add vsock tests, the CI will be ready for them.

👷 CI: Enable tokio-vsock tests on Linux

---

zbus_xmlgen/Cargo.toml
zbus_xmlgen/src/cli.rs
zbus_xmlgen/src/main.rs

Update `zbus-xmlgen` to use [`clap`](https://crates.io/crates/clap). This change converts the `--session`, `--system`, `--address`, and `file` arguments into subcommands.
Builds on https://github.com/dbus2/zbus/pull/499 to also add the `--split-interfaces` options.
- Improve help/documentation by adding descriptions/comments to arguments.
- Generate completions and a man page

zx: use clap for arg parsing

---

zbus_xmlgen/src/main.rs

Since code for `org.freedesktop.DBus` interfaces is not generated, direct the user to https://docs.rs/zbus/latest/zbus/fdo/index.html instead of silently skipping them. In addition, this adds more information, indicating which interfaces were generated; if the interfaces are written to different files, the filename is also printed.
Example output when writing all interfaces to the same file:
```
Skipping `org.freedesktop.DBus` interfaces, please use https://docs.rs/zbus/latest/zbus/fdo/index.html
Generated code for `org.freedesktop.UDisks2.Manager`
Generated code for `org.freedesktop.UDisks2.Manager.NVMe`
…
```
Example output when writing interfaces to the different files (default behavior):
```
Skipping `org.freedesktop.DBus` interfaces, please use …
```

 ✨ zx: improve user visible output

---

zbus/src/blocking/proxy/mod.rs
zbus/src/proxy/mod.rs
zbus_macros/src/proxy.rs
zbus_macros/tests/tests.rs
zvariant/src/lib.rs
zvariant/src/structure.rs
zvariant/src/tuple.rs

Fixes: https://github.com/dbus2/zbus/issues/542

Add SerializeTuple and use it for code generated by #[dbus_proxy]

---

zbus/Cargo.toml
zbus/src/connection/mod.rs
zbus/src/proxy/mod.rs
zbus/src/utils.rs

Replace the usage of OnceCell/Lazy from the once_cell crate with std types equivalents. The types were added before the current MSRV of zbus

zb: Replace once_cell usage

---

README.md
book/src/blocking.md
book/src/client.md
book/src/faq.md
book/src/server.md
zbus/README.md
zbus/examples/watch-systemd-jobs.rs
zbus/src/blocking/fdo.rs
zbus/src/blocking/mod.rs
zbus/src/blocking/object_server.rs
zbus/src/blocking/proxy/mod.rs
zbus/src/connection/mod.rs
zbus/src/fdo.rs
zbus/src/lib.rs
zbus/src/object_server/mod.rs
zbus/src/object_server/signal_context.rs
zbus/src/proxy/mod.rs
zbus/tests/e2e.rs
zbus_macros/Cargo.toml
zbus_macros/src/error.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/src/proxy.rs
zbus_macros/tests/tests.rs
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml
zvariant_utils/src/macros.rs

This removes the `dbus_` prefix before macros and macro attributes.
Fixes #477 
Fixes #478

remove dbus prefix

---

zbus/Cargo.toml

This allows it to be upgraded to any API-compatible versions. This implicitly also fixes a regression from e0c785a, where we ended up using API from a newer version of tokio than we depend on.

📌 zb: Pin tokio to only its major version

---

zbus/src/address/transport/autolaunch.rs
zbus/src/address/transport/launchd.rs
zbus/src/address/transport/mod.rs
zbus/src/address/transport/tcp.rs
zbus/src/address/transport/unix.rs
zbus/src/address/transport/vsock.rs

Let each transport impl have its own Display impl. This not only makes the code more readbable, but also makes it possible for users to display the transport types independently.

♻️  zb: Split Display impl of address::Transport

---

zbus/src/address/transport/mod.rs
zbus/src/address/transport/unix.rs

instead of byte vector. This seems like a better representation for the abstract socket name and typically the name is ASCII anyway.

🏷️ zb: Represent abstract socket name as OsString

---

zbus_names/src/error.rs
zbus_names/src/lib.rs
zbus_names/src/property_name.rs
zbus_xml/src/lib.rs
zbus_xml/tests/data/sample_object0.xml
zbus_xml/tests/tests.rs
zbus_xmlgen/tests/data/sample_object0.rs
zbus_xmlgen/tests/data/sample_object0.xml

This fixes #550 by adding a struct PropertyName to zbus-names. It's essentially a copy of the already existing struct MemberName but only checks for the name length instead of enforcing all name restrictions.
Also added/changed the appropriate tests.

🦺 zx: Allow unrestricted property names in zbus-xmlgen

---

zbus/Cargo.toml

The nix::unistd::Uid API requires the user feature, per https://docs.rs/nix/0.26.4/nix/unistd/struct.Uid.html
Somehow it worked out by luck as some other dependency was enabling that feature...

zb: Add missing nix feature

---

book/src/client.md

Update the `zbus-xmlgen` commands in the book to the new cli introduced in https://github.com/dbus2/zbus/pull/505

📝book: update zbus-xmlgen commands

---

zbus/src/lib.rs

🚸 zb: Provide `conn` alias for `connection` module

---

.github/workflows/rust.yml
zbus/Cargo.toml
zbus/src/blocking/connection/builder.rs
zbus/src/connection/builder.rs
zbus/src/connection/mod.rs

API that is only needed by bus implementations now gated behind this non-default cargo feature.
Fixes #480.

🚩 zb: Add `bus-impl` cargo feature

---

zbus/Cargo.toml

This is needed to eventually only use a single version of event-listener crate.

⬆️  Bump to async-broadcast 0.7.0

---

.github/workflows/rust.yml
book/src/connection.md
zbus/Cargo.toml
zbus/src/blocking/connection/builder.rs
zbus/src/blocking/connection/mod.rs
zbus/src/connection/builder.rs
zbus/src/connection/handshake.rs
zbus/src/connection/mod.rs
zbus/src/lib.rs
zbus/tests/e2e.rs

Given that typical users do not need this API, we don't enable it by default.

🚩 zb: Gate all p2p API behind a `p2p` feature

---

zbus/Cargo.toml

Not sure what enables these features for us in the CI and our Windows build doesn't seem to be failing but busd port picked it up:
https://github.com/dbus2/busd/actions/runs/7845734969/job/21410861140?pr=37#step:5:220

🚩 zb: Enable required feature flags of windows-sys crate

---

zbus/src/guid.rs
zbus/src/match_rule/mod.rs
zbus_names/src/bus_name.rs
zbus_names/src/error_name.rs
zbus_names/src/interface_name.rs
zbus_names/src/member_name.rs
zbus_names/src/property_name.rs
zbus_names/src/unique_name.rs
zbus_names/src/well_known_name.rs
zvariant/src/fd.rs
zvariant/src/into_value.rs
zvariant/src/object_path.rs
zvariant/src/owned_value.rs

When trying to implement the builder pattern working with `zvariant::Value` arguments, I encountered a strange compiler error about lifetimes when using generic functions.
The following simplified code shows the problem, with comments explaining the error encountered (functions `fail1`, `fail2`).
```rust
use zbus::zvariant;
/// A simplified builder to focus on the compile problem.
pub struct Values<'a> {
values: Vec<zvariant::Value<'a>>,
}
impl<'a> Values<'a> {
pub fn new() -> Self {
Self { values: Vec::new() }
}
/// Adds a value.
/// 
/// Accepts anything than can be converted into a `zvariant::Value` with
/// a sufficient lifetime.
pub fn value<V>(mut self, value: V) -> Self
where
V: Into<zvariant::Value<'a>>,
{
self.values.push(value.into());
self
}
}
// Using explicit lifetimes to …
```

🩹 fix impl (Try)From for owning values

---

book/src/client.md

Updates the [zbus_polkit](https://github.com/dbus2/zbus_polkit) link in the book, since the code has been moved in https://github.com/dbus2/zbus/pull/419. The [crates.io](https://crates.io/crates/zbus_polkit) pages also still point to this repository.

📝book: update zbus_polkit link

---

CONTRIBUTING.md

While contributors are asked to add a prefix indicating the packages being changed by a commit, this was not documented in the contribution guide.

📝 CONTRIBUTING: suggest package prefixes for commit messages

---

zbus/src/blocking/connection/builder.rs
zbus/src/connection/builder.rs

Since tokio currently [does not support Unix domain sockets on Windows][tuds], there is no reason to enable UDS support on Windows+tokio. This also fixes a build warning against rust nightly:
```rust
error: field `0` is never read
--> zbus\src\connection\builder.rs:45:16
|
45 |     UnixStream(UnixStream),
|     ---------- ^^^^^^^^^^
|     |
|     field in this variant
|
= note: `-D dead-code` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(dead_code)]`
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
|
45 |     UnixStream(()),
|                ~~
```
[tuds]: https://github.com/tokio-rs/tokio/issues/2201

🚩 zb: Disable UDS support on Windows for tokio

---

zbus_xmlgen/src/main.rs

Fixes an issue where instead of checking if `fdo_standard_ifaces` was empty, it was accidentally checked if the prefix string was empty. Found by (and thanks to) @Cobinja in https://github.com/dbus2/zbus/commit/35c15c8d9e8e730dee6bdbfa6997cd7d83a8f738#r138622943.
I totally blame clippy for not having a lint against this :)

🐛zx: correctly check if fdo ifaces is empty

---

zbus/examples/screen-brightness.rs

Fixes a typo in the `screen-brightness.rs` example of zbus.

✏️ zb: incresses → increases

---

.github/renovate.json
zbus_macros/src/iface.rs
zbus_macros/src/proxy.rs
zbus_xmlgen/src/main.rs
zvariant_derive/src/lib.rs
zvariant_derive/src/type.rs
zvariant_derive/src/value.rs

It gets a bit tiring to do this manually for all updates.

🤖 renovate: Automerge non-major updates

---

zvariant/src/serialized/data.rs

This would fail compilation on eg. windows because the FD generic does not actually exist there.
Reproduce via `cargo build --features="gvariant" --target=x86_64-pc-windows-gnu`

zvariant: Fix compilation of gvariant feature on non-unix platforms

---

zbus_macros/Cargo.toml
zvariant_derive/Cargo.toml

Otherwise, it breaks the build for folks who happen to have both zbus 3 and 4 in their dependency tree.
Fixes #652.

📌 zm,zd: Unpin zvariant_utils version in Cargo.toml files

---

.github/workflows/deploy.yml

We don't want any 3.x releases to overwrite the book.

🚀 CI: Only publish book changes for 4.x releases

---

zbus/src/blocking/proxy/mod.rs
zbus/src/proxy/mod.rs
zvariant/benches/benchmarks.rs
zvariant/src/ser.rs
zvariant/src/serialized/data.rs
zvariant/src/value.rs

This demonstrates a huge performance difference when using serde_bytes:
```
byte_array_ser          time:   [1.7867 µs 1.7883 µs 1.7901 µs]
change: [-99.922% -99.922% -99.922%] (p = 0.00 < 0.05)
```

⚡️ zv,internal: Make use of serde_bytes for byte arrays

---

.github/workflows/rust.yml
zbus/src/connection/handshake.rs

We now send `DATA`, `NEGOTIATE_UNIX_FD` and `BEGIN` commands at once. This reduces latency and hence improves performance.
It would have been the best to send all the commands at the same time, but seems dbus-daemon kick us out if we send multiple commands after it rejects the auth command. It wants us to negotiate the auth first. We could in theory just reconnect but that would require some architectural changes and rethinking the code.
Moreover cookie auth requires a round-trip to the server to get the cookie context first so we can't fully pipeline that one.
The server side is not possible to pipeline as it the server just responds to commands from the client and it can not assume that clients will always pipeline all commands.
Fixes #493.

⚡️ zb: Pipeline client-side handshake as much as possible

---

zbus_xmlgen/src/lib.rs
zbus_xmlgen/tests/data/sample_object0.rs
zbus_xmlgen/tests/data/sample_object0.xml

We started doing this already in cae1a65447 but it didn't cover all cases and we still sometimes end up with types that do not implement `serde::Deserialize`.
As a side-effect, this now also turns some of the normal method args to take references instead of values, which is a good thing.
Fixes #412.

🚑️ zx: Always use owned types for signal args

---

Cargo.lock
zbus_macros/Cargo.toml
zbus_macros/src/proxy.rs

This removes the unneeded dependency on `regex` in `zbus_macros`. I believe this code should be equivalent to the regular expression.  
- Loops over looking for any `&` as `is_match` just requires it a match anywhere in the string
- once found, strip off all leading spaces
- if they're equivalent, then we've found it
The only ambiguity I can think of being if the type contained symbols that regex would have considered as part of the name, but I think that'd only happen for tuples and the regex wouldn't match those due to considering it a capture group and not parentheses.

➖ zm: Remove regex dep

---

zbus/src/object_server/interface.rs

Also recommend what people should do when `dbus_interface` isn't enough.

📝 zb: Clearly document `Interface` being unstable API

---

Cargo.lock
zbus/Cargo.toml
zbus/src/blocking/connection/mod.rs
zbus/src/blocking/message_iterator.rs
zbus/src/blocking/proxy/mod.rs
zbus/src/connection/builder.rs
zbus/src/object_server/interface.rs
zbus/src/object_server/mod.rs
zbus/src/proxy/mod.rs

Ideally this dependency should be dropped/replaced, because it pulls old syn version, and is very unlikely to be ever updated. It is not as important while `zbus_macros` also depends on syn v1, though.

➖ zb: Remove derivative dep 

---

zbus/src/connection/socket/channel.rs

This fixes a regression from 5a6cdd00a8c19aabd32e25bb53a79c7d503078c6 where we used the wrong method name.

🚑️ zb: Fix build on Windows with p2p enabled

---

.github/workflows/rust.yml
book/src/connection.md
zbus/Cargo.toml
zbus/README.md
zbus/src/address/transport/mod.rs
zbus/src/connection/handshake/client.rs
zbus/src/connection/mod.rs
zbus/src/lib.rs
zbus/src/win32.rs

Turns out that the reference dbus implementation supports autolaunch fine and we don't need gdbus binary or special support for it. Hopefully, in the near future, [busd will also support it](https://github.com/dbus2/busd/issues/67).
This PR drops the `windows-gdbus` feature. This means we're no longer compatible with gdbus binary but that's not our fault that it can't handle handshake pipelining. I seriously doubt anyone uses this anyway.
Fixes #687.

🔥 zb: Drop `windows-gdbus` feature & support autolaunch address unconditionally

---

zbus/src/connection/builder.rs
zbus/src/connection/handshake/client.rs
zbus/src/connection/handshake/common.rs
zbus/src/connection/handshake/mod.rs
zbus/src/connection/handshake/server.rs
zbus/src/connection/mod.rs
zbus/src/connection/socket_reader.rs
zbus/src/fdo.rs
zbus/src/object_server/mod.rs

This avoids unnecessary round trips and makes the connection setup faster.

🔌 zb: Send `Hello` method as part of the handshake (client-side)

---

zbus/src/connection/builder.rs
zbus/src/connection/mod.rs
zbus/src/error.rs
zbus/src/fdo.rs
zbus/src/message/field.rs
zbus/src/message/mod.rs
zbus/src/object_server/interface.rs
zbus/src/object_server/mod.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/tests/tests.rs

Clients can expect calls to be handled in order they are sent. Although the specification doesn't explicitly state so  (https://gitlab.freedesktop.org/dbus/dbus/-/issues/179), bus implementations have respected message ordering. This can also be  expected when the bus and client are fully managed, as in p2p.
Add an option to avoid the default task spawning when dispatching methods on a specific interface.
This currently prevents parallel handling of other incoming calls which will have to wait for the method to return (current pending calls are still running in parallel).
Supersedes: #668

Make task spawning for method call optional

---

zbus/src/blocking/connection/builder.rs
zbus/src/connection/builder.rs
zbus/src/connection/mod.rs

This is to already be prepared for #731.

Add connection::Builder::auth_mechansim & deprecate connection::Builder::auth_mechansims

---

zvariant/README.md

Previously it was unclear that the `serde_repr` crate was required for unit enums to be serialized with the proper width as provided by a given `#[repr(_)]` annotation. Just adding a quick shout out to hopefully avoid confusion in the future.
Fixes #686

:memo: zv: document serde_repr usage for enums

---

zbus/src/connection/handshake/client.rs
zbus/src/connection/handshake/common.rs
zbus/src/connection/socket/tcp.rs

🚑️ Fix a few recent regressions

---

zbus/src/lib.rs
zbus_macros/src/lib.rs
zbus_names/src/lib.rs
zbus_xml/src/lib.rs
zvariant/src/lib.rs
zvariant_derive/src/lib.rs

Otherwise, the docs test will fail on latest Rust release:
```rust
---- zbus/src/lib.rs - doctests (line 37) stdout ----
error: struct `DictionaryGiverInterface` is never constructed
--> zbus/src/lib.rs:63:8
|
31 | struct DictionaryGiverInterface;
|        ^^^^^^^^^^^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> zbus/src/lib.rs:34:9
|
2  | #![deny(warnings)]
|         ^^^^^^^^
= note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`
error: method `give_me` is never used
--> zbus/src/lib.rs:67:8
|
34 | impl DictionaryGiverInterface {
| ----------------------------- method in this implementation
35 |     fn give_me(&self) -> Result<Dictionary> {
|        ^^^^^^^
error: aborting due to 2 previous errors
Couldn't compile the test.
failures:
zbus/src/lib.rs - doctests (line 37) …
```

🚨 docs: Allow dead code in doc samples

---

.github/workflows/rust.yml
zbus/src/object_server/mod.rs

`debug_assert!` is removed in release builds, along with any values computed inside it. This meant that since the use of `debug_assert!` in commit 7fc3ab7b8f69e21822a0d569222baba4b72de13f, the fdo interfaces weren't getting added for nodes for release profile. Let's use `assert!` instead.
Fixes #764.

🚑️ zb: Use `assert!` instead of `debug_assert!`

---

zbus/src/connection/builder.rs
zbus/src/connection/handshake/client.rs
zbus/src/connection/handshake/mod.rs
zbus/src/connection/handshake/server.rs
zbus/src/connection/mod.rs
zbus/src/connection/socket/channel.rs
zbus/src/connection/socket/mod.rs
zbus/src/connection/socket_reader.rs

Don't assume that only a single full message could be received at the end of the client handshake process. We may receive other messages too if the server is very quick in sending them (or batches them). Worst case scenario, we could also end up receiving partial messages, which would currently completely break the connection state.
Let's be a bit smart about this and ensure that we consume all the bytes that are received during the handshake process.
We are changing the type of the `already_received_bytes` arg of `connection::socket::ReadHalf::receive_message` and theoretically, this is an API break but given this is very new API, it's very unlikely that anyone implements Socket anyway and this change is needed to fix the issue at hand, let's not worry about it.

🎨 zb: Ensure all messsage bytes received during handshake are used

---

zvariant/src/dict.rs
zvariant/src/lib.rs

This change aims to partially solve #281 to expose an API for `zvariant::Dict` to iterate via a tuple of key and value, aka. (Value, Value) type.
However, because we have migrated to use `BTreeMap<K, V>` for `zvariant::Dict`'s internal representation, we still cannot use `f64` as keys based on the restrictions of `Ord` required by `BTreeMap::<K, V>::insert()` function signature.
```rust
pub fn insert(&mut self, key: K, value: V) -> Option<V>
where
K: Ord;
```
Since all `Basic` types are allowed in D-Bus specification, we still need to think of a way to allow users to correctly build up a `zvariant::Dict` whose signature is similar to `a{dv}`.

🚸 zv: Dict add iterator support

---

zbus/src/connection/handshake/client.rs

`xdg-dbus-proxy` [can't handle pipelining](https://github.com/flatpak/xdg-dbus-proxy/issues/21), hence we need to handle `NEGOTIATE_UNIX_FD` command's response before sending out `BEGIN` command and `Hello` method call message.
We should remote this as soon as flatpak is fixed and fix is available in major distros.

💩 zb: Hack to make connection handshake work inside Flatpak

---

zbus/src/lib.rs
zbus_macros/src/iface.rs

This fixes a regression introduced by 91abff76a964d9c2ba7907435886ee9810395d02, resulting in tasks not being spawned for methods by default.
Fixes #799.

🚑️ zm: Fix default value of `Interface::spawn_task_for_method`

---

Cargo.lock
zbus_macros/Cargo.toml
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml

`syn` upgraded to 2.x and zvariant_utils exposes that in its public API so major version needs to be bumped.

🔖 zu: Release 2.0.0

---

book/src/server.md
zbus/src/object_server/mod.rs
zbus/tests/e2e.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/src/proxy.rs
zvariant_utils/src/macros.rs

The common sub-attributes get proxied over and proxy-specific sub-attributes can be specified using `proxy` attribute (e.g `#[zbus(proxy(allow_interactive_auth))]`).
We are only adding this for `interface` and not the deprecated `dbus_interface`. Not only it saves us duplication, hopefully this will further encourage people to switch to `interface`.
Known limitations:
* Reference types in return values of `interface` methods won't work.
* Methods returning `object_server::ResponseDispatchNotifier` wrapper will do the same for proxy as well.
Fixes #236.

✨ zm: interface can now generate proxy for you

---

book/src/connection.md

seen at https://dbus2.github.io/zbus/connection.html

missing footer `:` in connection.md

---

zbus/src/abstractions/async_lock.rs
zbus/src/connection/handshake/client.rs
zbus/src/connection/mod.rs
zbus/src/utils.rs

While [the underlying issue in xdg-dbus-proxy][1] has already been fixed, it will take some time before the fix is released and is widely available. So let's add a workaround for now that makes message creation and sending an atomic operation, using an async semaphore if flatpak portal is detected.
[1]: https://github.com/flatpak/xdg-dbus-proxy/issues/46

💩 zb: Workaround for xdg-dbus-proxy's monotonic serial requirement

---

zvariant/src/dict.rs
zvariant/src/lib.rs
zvariant/src/value.rs

Dictionaries with variable length keys require a framing offset. The SerializeMap implementation already handles this, the manual serialization of dict entries used by Value does not. We now call directly into SerializeMap when serializing Value to align these serializations.
Unfortunately this requires adding two new methods to Value, similar to `serialize_value_as_seq_element` et al. To balance it out, we can remove `DictEntry`.
Closes #868

🐛 zv: Fix dictionary entry serialization from Values

---

zvariant/src/value.rs

the current implementation of `Hash` for `zvariant::Value` doesn't hold the property described in the rust rust standard library in [`Hash` and `Eq`](https://doc.rust-lang.org/std/hash/trait.Hash.html#hash-and-eq):
```rs
use std::hash::{DefaultHasher, Hash, Hasher};
fn main() {
let v1 = zvariant::Value::F64(0.);
let v2 = zvariant::Value::F64(-0.);
println!("{} == {} : {}", v1, v2, v1 == v2);
let mut hasher = DefaultHasher::new();
v1.hash(&mut hasher);
let h1 = hasher.finish();
let mut hasher = DefaultHasher::new();
v2.hash(&mut hasher);
let h2 = hasher.finish();
println!("{:#x} == {:#x} : {}", h1, h2, h1 == h2);
}
```
```txt
0. == -0. : true
0x3885e79ab4b1bb3a == 0xe3da94884cfc9c4 : false
```
implementing `Hash` for an `f64` comes with a host of annoying issues, like being able to insert …

🐛 implement `Hash` and `Eq` property for Value::F64

---

zbus/tests/e2e.rs
zbus_macros/src/iface.rs

If user specifies a Result type as return type of a method, the generated proxy should use the same error types. We might need to add an attribute to control in the future, as this as this may not always be what the user wants.
We should do this because if we hardcode the error type to be `zbus::Error`, the API will have to break if one decides to replace a `proxy` use with this new ability of `interface` and they had their `proxy` return a specific error type. This for example is the case for `zbus::fdo` API, which we want to convert in the future.
Speaking of API break, this change itself is an API break but practically speaking the chances of someone already making use of the newly added feature of generating proxy from interface is pretty low (on the Matrix channel people didn't even …

🥅 zm: interface-generated proxy should use the same error types

---

.github/workflows/deploy.yml

So old links to `server.html` will still work.

📝 book: Bring back `server.html` as symlink to `service.hmtl`

---

zbus_macros/src/iface.rs
zvariant_derive/src/dict.rs
zvariant_derive/src/lib.rs
zvariant_utils/src/case.rs

Also add some tests for case conversion
to ensure renamings are consistent

✨ zv: support kebab-case in rename_all

---

zvariant/Cargo.toml
zvariant/src/lib.rs
zvariant/src/type.rs

See also #98.
This PR implements `Type` on a bunch of types from the standard library and some chrono types.
I also added a helpful macro `impl_type!` that takes care of implementing `Type` and testing that the type and its repr are actually serialize-compatible.

✨ zv: Add more `Type` impls

---

zbus/Cargo.toml
zbus/src/blocking/connection/mod.rs
zbus/src/connection/mod.rs

Fixes #309.
I ended up naming it `Connection::graceful_shutdown` since `shutdown` felt too ambiguous with `close` to me. Happy to change if desired.
The included test is a little more tokio-integrated than most in the project, but since tokio was already a dev-dependency I'm hoping this is fine. I'm not aware of a different/better way to assert that an async function *doesn't* return.

✨ zb: Add Connection::graceful_shutdown

---

zbus/src/message/header.rs

When `SERIAL_NUM` wraps past `u32::MAX` back to zero, the conversion to `NonZeroU32` panics.
Fixes #946.

🚑️ zb: Gracefully handle serial number wrap

---

Cargo.toml
zvariant/benches/benchmarks.rs

* Enable debug for bench profile.
* Bump measurement time to 30 seconds.

🔨 zv: Improvements to benchmarks

---

Cargo.lock
zbus/Cargo.toml
zbus/benches/benchmarks.rs

We add separate benchmarks for header and body ser and de. They show the following results when compared to the main branch before #966:
```
message-ser/small       time:   [3.0693 µs 3.0745 µs 3.0801 µs]
change: [-56.616% -55.888% -55.132%] (p = 0.00 < 0.05)
Performance has improved.
Found 14 outliers among 100 measurements (14.00%)
1 (1.00%) low severe
2 (2.00%) low mild
4 (4.00%) high mild
7 (7.00%) high severe
message-ser/big         time:   [2.3432 ms 2.3506 ms 2.3576 ms]
change: [-14.648% -13.677% -12.583%] (p = 0.00 < 0.05)
Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
2 (2.00%) high mild
1 (1.00%) high severe
message-de/header       time:   [164.90 ns 165.33 ns 165.83 ns]
change: [-7.5284% -6.5826% -5.1958%] (p = 0.00 < 0.05)
Performance has improved. …
```

🔨 zb: Add benchmarks for Message ser/de

---

zvariant/src/ser.rs

Same as cde69bae38c5354c87d222c38d0019a7970fb418.

⚡️ zv: Simpler padding writing code

---

zvariant/src/deserialize_value.rs
zvariant/src/lib.rs
zvariant/src/serialize_value.rs
zvariant/src/str.rs
zvariant/src/structure.rs
zvariant/src/value.rs

JSON will decode a variant as a map and our `Value`'s `Visitor` implementation wasn't handling that. This resulted in us not being able to decode back our own generated JSON in case of variants inside variants.
Fixes #549.

🐛 zv: Fix de of recursive variants from JSON

---

zvariant/src/array.rs
zvariant/src/dbus/ser.rs
zvariant/src/gvariant/ser.rs
zvariant/src/lib.rs
zvariant/src/parsed/signature.rs
zvariant/src/structure.rs
zvariant/src/value.rs

* Don't check strings for embedded null bytes
* Avoid signature cloning in Value de
* Avoid an allocation in signature parser

⚡️ zv: A few more ser/de optimizations

---

zbus/src/connection/mod.rs

The test fails with tokio-vsock, which doesn't seem to send or flush the BEGIN command. More investigation needed.

add vsock connection tests

---

zvariant_derive/src/lib.rs
zvariant_derive/src/utils.rs
zvariant_utils/src/macros.rs

This PR adds support for multiple attribute list identifiers to `def_attrs!` macro from `zvariant_utils` and uses this in `zvariant_derive` to avoid mentioning `zvariant` when using macros out of `zbus` (as described in #820).

zv: Multiple lists support for derive macros.

---

book/src/service.md
zbus/src/blocking/mod.rs
zbus/src/blocking/proxy/mod.rs
zbus/src/lib.rs
zbus/src/proxy/builder.rs
zbus/src/proxy/mod.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/src/proxy.rs
zvariant_utils/src/macros.rs

These were deprecated in 4.0, so we remove it now for 5.0.

🔥 zm,zb: Drop deprecated `dbus_interface` & `dbus_proxy` macros

---

zbus/src/fdo.rs
zbus/tests/e2e.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/src/proxy.rs
zbus_macros/tests/tests.rs

This includes all types generated by `proxy` macro. Also add a sub-attribute to `proxy` attribute of `interface` to control visibility of `interface`-generated proxy types.
Unfortunately this means that the existing code will have to set the visibility explicitly to `pub` if they were relying on the generated proxy to be public. Good that we're in API break.

💥 zm,zb: `proxy` macro respects visibility

---

zbus/src/message/header.rs

Relaxed order is good enough here and SeqCst is an overkill.

⚡️ zb: Use relaxed load order for serial number fetch & add

---

zbus/tests/issue/issue_1015.rs
zbus/tests/issue/mod.rs
zvariant/src/type.rs
zvariant_utils/src/signature/fields.rs

In `DynamicDeserialize` impl for `Type`, if the given signature doesn't match the expected signature and the expected signature is a struct with a single field, match against the field's signature instead. This is needed when D-Bus message body consists of a single type and it is being deserialized as a single-field struct.
Fixes #1015.

🚑️ zv: More lenient check for signature match

---

Cargo.lock
zbus/Cargo.toml
zvariant/Cargo.toml
zvariant/src/type.rs

This adds a crate feature to `zbus` and `variant` called `"camino"`, which adds a derivation of `Type` for `camino::Utf8Path` and `camino::Utf8PathBuf`. It also adds `camino` as a dependency of `zvariant`.

➕ zb,zv: Add camino feature to impl `Type` for utf-8 path types

---

zbus/src/blocking/proxy/mod.rs
zbus/src/proxy/mod.rs
zbus_macros/src/proxy.rs

+ Fix some lifetimes in `Proxy` API.

💥 zb,zm: Drop unnecessary lifetimes on genarated signal streams

---

book/src/blocking.md
book/src/service.md
zbus/src/blocking/object_server.rs
zbus/src/connection/handshake/mod.rs
zbus/src/fdo/mod.rs
zbus/src/fdo/object_manager.rs
zbus/src/fdo/properties.rs
zbus/src/lib.rs
zbus/src/message/builder.rs
zbus/src/object_server/interface/interface_ref.rs
zbus/src/object_server/interface/mod.rs
zbus/src/object_server/mod.rs
zbus/src/object_server/signal_context.rs
zbus/src/object_server/signal_emitter.rs
zbus/src/proxy/mod.rs
zbus/tests/e2e.rs
zbus/tests/issue/issue_1015.rs
zbus/tests/issue/issue_173.rs
zbus/tests/issue/issue_310.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs
zbus_macros/tests/tests.rs

This PR first converts `SignalContext` to a `SignalEmitter`.
This it changes `interface` to generate a trait, `<InterfaceType>Signals`, that provides the same signal methods as user specifies but w/o the `SignalEmitter` argument. The macro also generates 2 implementations of this trait for:
* `InterfaceRef<InterfaceType>`
* `SignalEmitter`
The former is useful for emitting signals from outside the context of an interface method and the latter is useful for emitting signals from inside an interface methods.
Fixes #871.

✨ zm: interface now provides convenience API to emit signals

---

zbus/src/blocking/proxy/builder.rs
zbus/src/blocking/proxy/mod.rs
zbus/src/proxy/builder.rs
zbus/src/proxy/defaults.rs
zbus/src/proxy/mod.rs
zbus/tests/issue/issue_1015.rs
zbus_macros/src/proxy.rs
zbus_names/src/bus_name.rs

Rename `proxy::ProxyDefault` to `proxy::Defaults` and make it's constants strongly-typed.

💥 `proxy::ProxyDefault` overhaul

---

zbus/src/connection/connect/mod.rs

This mainly fixes a regression from #989.

Fix connection breakage

---

zbus/src/blocking/connection/builder.rs
zbus/src/connection/builder.rs
zbus/src/connection/handshake/client.rs
zbus/src/connection/handshake/command.rs
zbus/src/connection/handshake/common.rs
zbus/src/connection/handshake/mod.rs
zbus/src/connection/handshake/server.rs
zbus/src/connection/mod.rs
zbus/src/connection/socket/channel.rs
zbus/src/connection/socket/mod.rs
zbus/src/connection/socket/tcp.rs
zbus/src/connection/socket/vsock.rs
zbus/src/lib.rs

Now that we're down to only two authentication mechanisms with one of them being no-authentication, this really makes sense since we can just autodetect what authentication method to use for a specific socket type on a specific platform.
This also simplifies the handshake logic and will allow us to pipeline the whole client-side handshake in the future, when we can drop the xdg-dbus-proxy [workarounds].
As they say in the famous Queen song:
Hey! One man, one goal
Ha, one mission
One heart, one soul
Just one solution
One flash of light
Yeah, one God, one vision
One flesh, one bone, one true religion
One voice, one hope, one real decision
Whoa, whoa, whoa, whoa, whoa, whoa
Give me one vision, yeah
Fixes #731.
[workarounds]: https://github.com/dbus2/zbus/issues/781

🛂 zb: Only support one authentication method at a time

---

zbus/src/connection/handshake/auth_mechanism.rs
zbus/src/connection/handshake/client.rs
zbus/src/connection/handshake/command.rs
zbus/src/connection/handshake/server.rs

Now that we don't support all authentication mechanisms described in the spec, we'll get a parse error on receiving an unsupported mechanism. Let's use the raw string type for the mechanism field in the Rejected command to avoid this.
We do so in a way that limits allocations, especially on the server-side, which might need to reject a lot of connections and it will have more impact there.

🛂 zb: Use string type for auth mechanisms in Rejected cmd

---

zbus/src/connection/connect/mod.rs
zbus/src/connection/connect/win32.rs

Only box the internal future, where recursion happens and hence boxing is needed (only on Windows).

⚡️ zb: Drop unneeded boxing of a future

---

zbus_names/src/bus_name.rs

Otherwise, it breaks the assumption of the internal `QuickFields` API in zbus and we end up with failing to get the destination field from message.
Fixes #1055.

🚑️ zn: Ensure BusName is constructed from given Str

---

zbus/Cargo.toml

This is just a proxy feature for `zvariant`'s `serde_bytes` feature.
Fixes #1052.

🚩 zb: Add `serde_bytes` Cargo feature

---

zbus/src/message/body.rs
zbus/src/message/builder.rs
zbus/src/message/fields.rs
zbus/src/message/header.rs
zbus/src/message/mod.rs
zbus/tests/basic.rs
zbus/tests/e2e.rs
zvariant_utils/src/signature/mod.rs

We have a Signature variant the represents empty body, Unit and since the spec says:
> If omitted, it is assumed to be the empty signature "" (i.e. the body
> must be 0-length).
it makes sense to simply assume `Signature::Unit` when the signature is missing from the message headers.
We do ensure that we don't serialize `Signature::Unit`.

🚸 zb: Message body signature now mandatory

---

zbus/Cargo.toml
zbus/src/lib.rs

"cargo build" in zbus/zbus (with default features) fails, there are missing cfg conditions.

🩹 zb: Fix missing cfg(blocking-api)

---

zbus/Cargo.toml

This was supposed to be a default feature, I had just forgotten to add it.

🚩 zb: Add `blocking-api` to default features

---

zbus_xmlgen/src/lib.rs
zbus_xmlgen/tests/data/sample_object0.rs

This was the default visibility until `proxy` macro started to respect the visibility of the input trait. Let's set it to `pub` by default as that's what most folks will likely want. If not, they can easily modify it.

🩹 zx: Set visibility of generated proxy to pub

---

.github/workflows/deploy.yml
book/src/introduction.md

Also remove disclaimer about zbus being unix-specific as its not been true for a long time.

👷 CI: Update zbus version for book generation

---

Cargo.lock
zbus_macros/Cargo.toml
zvariant/benches/benchmarks.rs
zvariant/src/lib.rs
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml
zvariant_utils/src/signature/mod.rs

This brings in 2 benefits:
* The signature parsing code is now up to 30% faster. This directly translates to encoding/decoding speed of variants (used extensively in the D-Bus/gvariant world). This is the path that saw the least optimization in 5.0.0.
* Removal of `nom` and `minimal-lexical` deps (recently introduced in 5.0.0). Apparently `winnow` was already our indirect dependency so no new deps needed.

⚡️ zu: Switch from `nom` to `winnow` for signature parsing

---

Cargo.lock
zbus/Cargo.toml
zbus_macros/Cargo.toml
zvariant/Cargo.toml
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml

Also release zvariant and zbus to stop pinning zvariant_utils version.

🔖  zvariant_utils release 3.0.1, and zvariant and zbus 5.0.1

---

zbus/Cargo.toml
zbus/src/abstractions/mod.rs
zbus/src/abstractions/process.rs
zbus/src/address/mod.rs
zbus/src/address/transport/mod.rs
zbus/src/address/transport/unixexec.rs
zbus/src/connection/builder.rs
zbus/src/connection/socket/command.rs
zbus/src/connection/socket/mod.rs
zbus/tests/unixexec.rs

Add initial support for the [unixexec](https://dbus.freedesktop.org/doc/dbus-specification.html#transports-exec) transport (#325). ~~Currently this is **only implemented when the `tokio` feature is enabled**.~~ Edit: Support for the `async-io` runtime has also been implemented in later revisions.

✨ zb: Add support for `unixexec` transport

---

Cargo.lock
zbus/Cargo.toml
zbus/benches/benchmarks.rs
zbus/src/address/mod.rs
zbus/src/guid.rs
zbus_names/Cargo.toml
zbus_names/benches/benchmarks.rs
zbus_names/src/bus_name.rs
zbus_names/src/error_name.rs
zbus_names/src/interface_name.rs
zbus_names/src/member_name.rs
zbus_names/src/property_name.rs
zbus_names/src/unique_name.rs
zbus_names/src/well_known_name.rs
zvariant/Cargo.toml
zvariant/benches/benchmarks.rs
zvariant/src/error.rs
zvariant/src/object_path.rs

Since winnow is now our dependency, it'd be best to make full use of that everywhere and use it to verify/parse all string types: zbus_names::*, zvariant::ObjectPath, zbus::Address etc.
Fixes  #1070.
---
TODO:
* Replace `from_options` constructors of all address transport types with winnow parsers, we can use in the `FromStr` impl of `Address`.
* Escape (% decode) all values in address strings as part of the winnow parser upfront.

Use `winnow` for parsing all strings

---

zbus/tests/issue/issue_310.rs
zbus_macros/src/iface.rs

Because they never change.
Currently the following
```rust
pub struct AccessInterface {}
#[zbus::interface(name = "org.freedesktop.impl.portal.Access")]
impl AccessInterface {
#[zbus(property(emits_changed_signal = "const"), name = "version")]
fn version(&self) -> u32 {
1
}
}
```
Would generate a `version_changed` and a `version_invalidate` even if the property never changes. 
This is current situation https://bilelmoussaoui.github.io/ashpd/ashpd/backend/account/struct.AccountInterface.html and with the changes proposed in this PR, the problem is fixed.

zm: Don't generate signals for interface const properties

---

.github/renovate.json

We're a library so micro and nano versions don't really affect our users and renovating creating PRs for every single release of all deps create a lot of noise.
This also means that we can now disable automerge, since they were only enalbed for micro and nano versions.

🤖 renovate: Only major and minor version updates

---

zbus/Cargo.toml
zbus_macros/Cargo.toml
zbus_names/Cargo.toml
zbus_xml/Cargo.toml
zbus_xmlgen/Cargo.toml
zvariant/Cargo.toml
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml

Require a slightly older and slightly more universally available Rust release. Rust 1.81 doesn't seem to have many features that zbus would likely need.
Fixes https://github.com/dbus2/zbus/issues/1107.

⬇️ all: Reduce `rust-version` to `1.80`

---

.github/renovate.json

This reverts commit 9db949a194ade49a209c6776539b47b900a8e7c0.
Turns out this wasn't the way to skip micro and nano updates. It only skipped our custom title for such updates instead. 🤦 I gotta find a way to do this right.

Revert "🤖 renovate: Only major and minor version updates"

---

zbus_names/src/bus_name.rs
zbus_names/src/error.rs
zbus_names/src/error_name.rs
zbus_names/src/interface_name.rs
zbus_names/src/member_name.rs
zbus_names/src/property_name.rs
zbus_names/src/unique_name.rs
zbus_names/src/well_known_name.rs

Let's deprecate specific name parsing errors in favor of one generic one that doesn't allocate. Also add a separate variant for name conversion errors as they're different from parsing errors.

🚸 zn: Streamline Error API

---

zbus_names/src/bus_name.rs
zbus_names/src/well_known_name.rs

Currently we're just returning the error from the WellKnownName parser, which can be confusing cause we're expect either a unique name or a well-known name.
Let's return a more appropriate error message in this case.

🥅 zn: More appropriate error on bus name parsing failure

---

zvariant/src/owned_value.rs
zvariant/src/value.rs

While `try_clone` should generally be used, there are times when `Clone` is really needed. Given that the chances of `try_clone` failing are pretty low these days, let's implement `Clone` based on `try_clone` than panics on `try_clone` failure.
Fixes #1078.

🏷️ zv: Implement Clone for *Value

---

zbus/src/connection/socket_reader.rs

Otherwise, we just end up with a lot of noise in the logs.

🔊 zb: Don't log error on broadcasting on generic message channel

---

zbus/Cargo.toml

instead of the target OS. Originally, this dep was only needed by Mac, which is not our prime target so it was ok to tie its use to Mac. But now we need it also on Linux (our prime target) but only if `async-io` is needed. This means that with the current setup, we end up making tokio users (a big majority of our users) also needlessly depend on it.

➖ zb: Tie async-process dep to async-io feature

---

CONTRIBUTING.md

Instead of configuring a non-standard location as the hooks dir. Otherwise, gimoji (and any other git hooks user may want to use) will not work.

👷 CONTRIBUTING: Suggest to copy the git hooks

---

zbus/src/fdo/introspectable.rs
zbus/src/fdo/object_manager.rs
zbus/src/fdo/peer.rs
zbus/src/fdo/properties.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs

Introspection strings are part of the binary and can have an impact on the binary size. This change allows to disable the addition of docs in the introspection for cases where there interface is well-known/well-documented.
For example, this will allow `busd` binary to shed 26 KB.

⚡️ zm: interface allows to disable docs in introspection + do that for fdo interfaces

---

zbus/src/connection/mod.rs
zbus/src/match_rule/mod.rs

This allows LTO to remove the proxy-side code from the binary if the users isn't directly using proxy APIs. On busd, this reduces the binary size by 200KB.

⚡️ zb: Don't use proxies in connection code

---

zbus_macros/Cargo.toml

It's just a proxy feature for zvariant and only needed to fix the build in the root workspace when building with `--features gvariant`.
Fixes #1125.

🚩 zm: Add `gvariant` feature flag

---

zvariant_utils/src/signature/child.rs
zvariant_utils/src/signature/fields.rs
zvariant_utils/src/signature/mod.rs
zvariant_utils/src/signature/tests.rs

* Turn Signature's size methods `const`.
* Add `Signature::to_string` that shadows `ToString::to_string` implementation coming from `Display` impl, that avoids reallocations during the string serialization process.

⚡️ zu: A few Signature micro optimizations

---

zvariant/src/dbus/de.rs
zvariant/src/lib.rs
zvariant/src/utils.rs

The range check would fail on NAN, INFINITY and NEG_INFINITY even if they are completely valid things to decode.
This does not promise that an encoded NAN will be bit-wise identical as the decoded NAN, but if signalling NAN is used that precisely the user can have a handful of more interesting problems.
Fixes #1145.

🐛 zv: Allow f32::NAN to be decoded too

---

zbus/src/fdo/object_manager.rs
zbus/src/fdo/properties.rs
zbus/src/object_server/interface/mod.rs
zbus/src/object_server/mod.rs
zbus/src/object_server/node.rs
zbus/tests/e2e.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs

This allows for fine-grained connecting-UID checking, in order to be able to control who is able to access property values.

✨ zb,zm: Support Option<Header<'_>> parameter in property getters

---

zbus/src/fdo/properties.rs
zbus/src/object_server/interface/mod.rs
zbus/src/object_server/node.rs
zbus/tests/e2e.rs
zbus_macros/src/iface.rs
zbus_macros/src/lib.rs

Along with all the other special parameter types that methods currently support (connection, object_server and signal_emitter).

✨ zb,zm: Support special args in interface property setters

---

Cargo.lock
zvariant/Cargo.toml
zvariant/src/lib.rs

I believe our own tests combined with fuzzing in the CI, is more than enough testing for gvariant encoding/decoding. So let's avoid the complexity of depending on a system library (even if it's only a dev-dep).

🔥 zv: Drop dev dependency on glib

---

CONTRIBUTING.md
zbus_xmlgen/src/lib.rs

When `rustfmt` is not installed or exits with a failure, print a warning message and continue with the unformatted generated code, instead of returning an empty string.
Closes: https://github.com/dbus2/zbus/issues/1122

🐛 zx: use unformatted code for rustfmt failure

---

zbus/src/message/builder.rs
zbus/src/message/fields.rs
zbus/src/message/header.rs
zbus/src/message/mod.rs

Right now cloning a header involves cloning the `PrimaryHeader` (cheap,
mostly POD), and then cloning the `Fields`, which can be somewhat
complex, as it involves cloning all the strings and the signature, which
if dynamic could be rather costly.
From things coming from a message, strings are always `Borrowed` so the
cloning is cheap, so the only expensive thing is cloning the signature.
Using `Cow` for it looks sensible, it's what `Str` is doing internally
already, effectively.

⚡️ zb: Make header cloning cheaper

---

Cargo.toml
zbus/Cargo.toml
zbus_macros/Cargo.toml
zbus_names/Cargo.toml
zbus_xml/Cargo.toml
zbus_xmlgen/Cargo.toml
zvariant/Cargo.toml
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml

Lowers the MSRV of all packages to 1.77 as per https://github.com/dbus2/zbus/issues/1107#issuecomment-2573181948. I decided to introduce it as a workspace variable to reduce the duplication across the packages.

Lower MSRV via workspace configuration

---

.github/pull_request_template.md

This will ease contributions because for obvious PRs, the contributor can just leave the template in the description.

🚸 Make PR template a comment

---

.github/workflows/rust.yml

This reverts commit dd6de5b8a80fc97a6020d0f73e4c5f71362fbcfc.
Also change the job to use 1.77.0, our current MSRV.

Revert "🔥 CI: Drop now unneeded MSRV check"

---

zbus_macros/src/iface.rs

Naming the optional header parameter 'header' several times for different property getters collides with the 'header` local argument of the generated get_all() function. Obvious workaround is don't name your special parameter 'header'.
This is easily fixed by simply wrapping each getter code block generated for get_all() in its own scope.

🐛 zm: Fix generated get_all() function

---

zbus_macros/src/proxy.rs

The passed strings just need to satisfy the inner lifetime of the proxy.

🐛 zm: Drop unnecessary 'static lifetime requirements in proxy

---

zbus_macros/src/iface.rs

I am using zbus to define an inteface method, like this:
```rust
#[zbus::interface(name = "public.settings")]
impl SettingsInterface {
async fn set_var(
&self,
originator: &str,
object: &str,
interface: &str,
arguments: &str,
) {
//...
}
}
```
This method is called with with the `NoReplyExpected` flag. However zbus generates a reply, which ended up in an error shown in `dbus-monitor`: 
```
Rejected send message, 0 matched rules; type="method_return", sender=":1.16" ...
```
I used `cargo expand` to see what code is generated by the interface macros and found something like this:
```rust
let reply = self.set_var(originator, object, interface, arguments).await;
let hdr = message.header();
connection.reply(&hdr, &reply).await
```
The `connection.reply()` method is called in every case. So i …

🩹 zm: do not reply if no-reply-expected flag is set

---

zvariant/src/into_value.rs

This PR mainly fixes Value not implementing From for Arced or Cowed strs.
Additionally I replaced the manual implementations of `From<String>` and `From<&'v String>` with the macro one.
I think this makes the PR not atomic anymore, sorry about that. 😅
fixes #1234

zv: Add missing From implementations for Value::Str

---

zbus/src/connection/handshake/command.rs

This fixes a regression from b792340.
Fixes #1216.

🐛 zb: Correctly format list of accepted auth mechanisms

---

zvariant_derive/src/value.rs

Otherwise, we end up not accepting negative values for enum discriminants because `syn` parses them as `Expr::Unary`. Same for binary operations (e.g `1 << 2`).

🐛 zd: Don't assume enum discriminant to be always a literal

---

Cargo.lock
zbus/Cargo.toml
zbus/src/blocking/message_iterator.rs
zbus/src/blocking/proxy/mod.rs
zbus/src/connection/mod.rs
zbus/src/connection/socket/command.rs
zbus/src/connection/socket/tcp.rs
zbus/src/connection/socket/unix.rs
zbus/src/connection/socket/vsock.rs
zbus/src/lib.rs
zbus/src/message_stream.rs
zbus/src/proxy/mod.rs
zbus_macros/src/iface.rs

I took a quick look at replacing the dev-dependency as well, but it looks like that's harder, and also not as useful. (the first roadblock I found was `futures_lite::StreamExt::try_for_each` using a different signature from `futures_util::TryStreamExt::try_for_each` that's less helpful if the closure itself returns a future)
Fixes https://github.com/dbus2/zbus/issues/1242.

zb: Replace futures-util runtime dependency with futures-lite

---

zvariant/src/into_value.rs

When creating a Value from a borrowed vec or slice using Value's From implementation, the compiler would wrongfully assume, that the created value has the same lifetime, even though the input gets cloned when creating the Array struct.
This PR makes the impl assign a new lifetime to the cloned value.
If I've messed up the gitmoji again, please let me know :)
```rust
use std::collections::HashMap;
use zvariant::Value;
fn main() {
println!("{:?}", func());
}
// 'a could also be replaced with 'static since Value is supposed to own all its data here
fn func<'a>() -> HashMap<&'static str, Value<'a>> {
let mut map = HashMap::new();
let vec = vec!["Hello", "World", "!"];
// this works because the From<Vec<V>> impl only uses the lifetime of Value
map.insert("some_key", vec.clone().into());
// …
```

🐛 zv: fix wrong lifetime when creating a Value from &Vec and &[]

---

zvariant_derive/src/dict.rs
zvariant_derive/tests/tests.rs

..in the struct deriving `DeserializeDict`.
Fixes #1252.

🐛 zd: Prefix a local variable w/ `__` so it doesn't conflict w/ fields

---

zvariant/src/lib.rs
zvariant_derive/src/dict.rs
zvariant_derive/src/lib.rs
zvariant_derive/src/utils.rs
zvariant_derive/src/value.rs

- Support enums without explicit values
- Support string representation for enums

✨ zd,zv: `Value` derive improvements for enums

---

zbus_xml/src/lib.rs

This fixes parsing large dbus specifications
Specifically,
https://github.com/PackageKit/PackageKit/blob/main/src/org.freedesktop.PackageKit.Transaction.xml currently results in "Error: QuickXml(TooManyEvents(1024))"

🐛 xmlgen: Raise XML parsing buffer size

---

Cargo.toml
zbus/Cargo.toml
zbus_macros/Cargo.toml
zbus_names/Cargo.toml
zbus_xml/Cargo.toml
zbus_xmlgen/Cargo.toml
zvariant/Cargo.toml
zvariant_derive/Cargo.toml
zvariant_utils/Cargo.toml

Move dependencies to workspace.
It will facilitate a future upgrade of dependency.

🧑‍💻 all: Use workspace dependencies

---

zbus/benches/benchmarks.rs
zbus/src/message/body.rs

We saw performance uplifts in the range of 10-15% in parsing events just by not cloning, reparsing the signature every time a body was created.
Hopefully it's a small enough change that it's easy to review.
This directly reduces the cost of calling `Body::new(...)` by 90-95%.

⚡️zb: don't clone signature when creating body

---

zbus_xmlgen/src/main.rs

Clippy:
```rust
warning: called `Iterator::last` on a `DoubleEndedIterator`; this will needlessly iterate the entire iterator
--> zbus_xmlgen/src/main.rs:101:22
|
101 |                     .last()
|                      ^^^^^^ help: try: `next_back()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last
= note: `#[warn(clippy::double_ended_iterator_last)]` on by default
```

⚡️ zx: Remove a needless iteration

---

zbus/src/message/builder.rs

Allow overriding serial/reply_serial in the message builder. Per the linked issue this is to support more low-level zbus tools, like a bus-to-bus grafter.
Fixes #1317.

✨ zb: Expose low-level serial fields in builder

---

zbus/src/fdo/stats.rs

The return value of the methods were wrong so we fix it now but since that involves (theoretically) breaking the API, we go one step further and provide a more specific (and hence nicer) API.
Fixes #1341.

🚑️ zb: Fix fdo::StatsProxy method return values

---

zvariant_derive/src/lib.rs
zvariant_derive/src/value.rs

Previously, setting these values would not apply to implementations of From and TryFrom when converting between a type and Value/OwnedValue. This change makes it so using rename or rename_all will apply to these traits.
Closes #320

✨ zd: Make rename & rename_all work on Value/OwnedValue

---

book/src/faq.md
zbus/README.md
zbus/src/fdo/dbus.rs
zbus/tests/e2e.rs
zvariant/src/dbus/de.rs
zvariant/src/dbus/ser.rs
zvariant/src/dict_utils.rs
zvariant/src/gvariant/de.rs
zvariant/src/gvariant/ser.rs
zvariant/src/lib.rs
zvariant/src/str.rs
zvariant/src/value.rs
zvariant_derive/src/lib.rs
zvariant_derive/tests/no_prelude.rs
zvariant_derive/tests/tests.rs

Instead make it possible to use `serde::{Serialize, Deserialize}` directly when (de)serializing a custom struct as an `a{sv}` type.
Fixes #1344, #73, #85, #856.

Deprecate *Dict derive macros

---

zbus/src/fdo/stats.rs

Now that we can use serde derives directly, we can make use of the `flatten` attribute and have a very strongly-typed API for the statistics standardized by the D-Bus specification while still parsing and returning any bus broker specific statistics returned by these calls.

🚸 zb: fdo::StatsProxy methods now return structs

---

zbus/src/connection/socket/channel.rs
zbus/src/connection/socket/mod.rs
zbus/src/connection/socket/unix.rs
zbus/tests/basic.rs

Add support for the ProcessFD key in `org.freedesktop.DBus.GetConnectionCredentials` to zbus (and thus to busd) by adding the socket pidfd to `ConnectionCredentials` in `socket::unix::get_unix_peer_creds_blocking`.

Support ProcessFD in fdo::DBus::get_connection_credentials'

---

zbus_macros/src/iface.rs

Avoids "missing documentation for a method" when -W missing-docs enabled in user code.
The documentation added is similar to the wording from the `#[interface]` macro documentation for the PROP_changed methods.
Thanks for a great crate!

📝 Document generated prop_changed and prop_invalidated methods

---

Cargo.toml
book/src/faq.md
zbus/Cargo.toml
zbus/src/fdo/dbus.rs
zbus/tests/e2e.rs
zbus_macros/Cargo.toml
zvariant/src/lib.rs
zvariant_derive/src/dict.rs
zvariant_derive/src/lib.rs

Turn `SerializeDict` and  `DeserializeDict` wrappers around serde derives and un-deprecate them.
For simpler cases, they're pretty good and now that we've made them wrappers around serde derives, maintainance shouldn't be an issue. We will no longer need to add new attributes because if people would want any, they should just use the serde derives directly.

✨ zd: Simplify & un-deprecate SerializeDict & DeserializeDict

---

Cargo.lock
zbus/Cargo.toml
zvariant/Cargo.toml
zvariant_derive/Cargo.toml

- **⬆️  all: Bump micro version in Cargo.lock**
- **🔖 zv,zd: Release 5.5.2**

🔖 zv,zd: Release 5.5.2

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
zbus/src/connection/socket/unix.rs
zbus/src/win32.rs
zvariant/src/utils.rs
zvariant/tests/common.rs
zvariant/tests/number/f64_value.rs
zvariant/tests/number/mod.rs

For whatever reason the nix::sys::socket::sockopt::PeerPidfd is only available to target_os = "linux", so properly guard the code using it against that.
Fixes: 3602dcbb ("✨ zb: Add ProcessFD/pidfd to peer ConnectionCredentials")

🐛 zb: Fix build on Android by limiting PeerPidfd to linux

---

zvariant/src/file_path.rs
zvariant/src/lib.rs

Add a new `FilePath` type to serve as a thin abstraction that handles (de)serialization of a file path as a byte array, since en/decoding of strings is limited to only UTF-8 characters in both D-Bus format and serde API.
Fixes #977.

🏷️ zv: Add FilePath type

---

zbus_macros/src/proxy.rs

Fix #1312 
In the `proxy` macro, support applying attributes to the related methods of the same property. This ensures that common attributes, such as `#[doc = "..."]` and `#[cfg(...)]`, can be applied to both the getter methods `receive_<property>_changed` and `cached_<property>`.
```rust
/// Test property for testing.
#[cfg(test)]
#[zbus(property)]
fn property(&self) -> fdo::Result<Vec<String>>;
```
will generates
```diff
#[doc = " Test property for testing."]
#[cfg(test)]
#[allow(clippy::needless_question_mark)]
pub fn property(&self) -> fdo::Result<Vec<String>> { ... }
+#[doc = " Test property for testing."]
+#[cfg(test)]
#[doc = "Get the cached value of the `Property` property, or `None` if the property is not cached."]
pub fn cached_property(
&self,
) -> ::std::result::Result< …
```

✨ zm: Copy attributes to `receive_*_changed` and `cached_*` methods

---

zvariant/src/type/libstd.rs

Fixes build on platforms without 64-bit atomics, such as `powerpc-unknown-linux-gnu`.
Fixes: #1390

🐛 zv: Fix build on platforms without 64-bit atomics

---

zbus/benches/benchmarks.rs
zbus_names/benches/benchmarks.rs
zvariant/benches/benchmarks.rs

Instead of deprecated `criterion::black_box`.

👽️ zb,zv,zn: Use `std::hint::black_box` in benchmarks code

---

zbus_names/src/error_name.rs

Error names have same constraints as *interface* names.
Trivial update resolving tautological statement, now matches dbus spec.

📝 zn: doc typo

---

zvariant/src/dbus/ser.rs
zvariant/src/gvariant/ser.rs
zvariant/tests/dict_value.rs

This fixes a regression that was exposed by 56cbb1f64.
Fixes #1417.

🚑️ zv: Check signature before serializing struct as a u8

---

zbus/src/blocking/connection/builder.rs
zbus/src/connection/builder.rs
zbus/src/connection/mod.rs
zbus/src/fdo/dbus.rs

By default names are requested with ReplaceExisting and DoNotQueue. We add to builder methods to control whether the ReplaceExisting and AllowReplacement bits are set.

✨ zb: Allow overriding some request name flags

---

zbus/src/fdo/dbus.rs
zbus/src/fdo/mod.rs

In 6.0 this will be the return type of start_service_by_name. For now, just provide a TryFrom<u32>. We want to use it in busd already though.
---
From https://github.com/dbus2/busd/pull/238#discussion_r2201345696

🧑‍💻 zb: add fdo::dbus::StartServiceReply type

---

zbus_macros/src/lib.rs

Feel free to convert this to a  documentation request issue rather than merging this PR.

📝 zm: Mention receive_X_changes in `proxy` docs

---

zbus/Cargo.toml
zbus/src/utils.rs

Otherwise, any blocking calls in the application code can block our
internal tasks. This is breaking our "we won't launch threads behind
your back" promise a little but its only limited to blocking API and
therefore worth the benefit of not unexpectedly stopping to work.
Fixes #1512.

🧵 zb: Launch a multi-threaded tokio runtime for blocking

---

zbus/tests/unixexec.rs

👷zb: exclude unixexec test on win32
