- .github/workflows/release.yml
Uses https://github.com/marketplace/actions/tag-to-release
---
> CI: Add action to create a release based on annotated tags

- zvariant/src/lib.rs
- zvariant/src/optional.rs
> zv,docs: Add example for `Optional`

- zvariant/src/basic.rs
- zvariant/src/type.rs
> zv: Impl Type for std Duration and NonZero*

- zbus/Cargo.toml
- zbus_macros/Cargo.toml
- zvariant/Cargo.toml
- zvariant_derive/Cargo.toml
- zvariant_utils/Cargo.toml
> Prep zbus, zvariant and zvariant-utils releases

- .github/workflows/rust.yml
- zbus/Cargo.toml
- zbus/src/abstractions/executor.rs
- zbus/src/address.rs
- zbus/src/connection.rs
- zbus/src/connection_builder.rs
- zbus/src/proxy_builder.rs
- zbus/src/utils.rs
- zbus_macros/Cargo.toml
- zbus_macros/src/proxy.rs
- zbus_names/Cargo.toml
- zbus_polkit/Cargo.toml
- zbus_xmlgen/Cargo.toml
- zvariant/Cargo.toml
- zvariant/src/encoding_context.rs
- zvariant/src/gvariant/ser.rs
- zvariant_derive/Cargo.toml
- zvariant_utils/Cargo.toml
MSRV bump was not planned for this PR but yet another [dep bumped their MSRV](https://github.com/dbus2/zbus/actions/runs/5027953247/jobs/9018085702) so after consulting with Tauri devs, I decided to bump the MSRV already (we were supposed to do that soon anyway).
---
> Simplify futures at connection init + drop run_in_thread internal utility + MSRV bump

- zbus/src/message_stream.rs
Add getter and setter for message queue capacity.
Related: #350.
> ✨ (zb): Add `MessageStream::{max_queued,set_max_queued}`

- zbus/src/connection_builder.rs
- zvariant/src/gvariant/de.rs
- zvariant/src/gvariant/ser.rs
- zvariant/src/type.rs
- zvariant/src/value.rs
> Some size related fixes

- book/src/connection.md
> 📝 (book): Update Connection::new_for_address reference

- book/src/blocking.md
- book/src/client.md
- book/src/connection.md
- book/src/faq.md
- book/src/server.md
- zbus/src/connection_builder.rs
> 📝 zb: Add IBus example for `ConnectionBuilder::address`

- zbus/src/blocking/fdo.rs
- zbus/src/fdo.rs
- zbus/src/guid.rs
> Improve `Guid` deserialization

- zbus/src/signal_context.rs
- zbus_macros/src/iface.rs
> ✨ zb,zm: Allow unicast signals through the dbus_interface

- zbus_names/src/bus_name.rs
- zbus_names/src/error_name.rs
- zbus_names/src/interface_name.rs
- zbus_names/src/lib.rs
- zbus_names/src/member_name.rs
- zbus_names/src/unique_name.rs
- zbus_names/src/utils.rs
- zbus_names/src/well_known_name.rs
- zvariant/src/str.rs
Plus deduplicate some code with macros.
> zn: implement Str <-> names conversinos

- zbus/src/match_rule.rs
- zbus/src/message_builder.rs
- zbus/src/raw/socket.rs
> :ambulance: zb: Handle 0 bytes received from socket + 2 other small changes

- zbus/src/fdo.rs
> Some fixes to fdo proxies

- zvariant/src/lib.rs
- zvariant/src/type.rs
> 🚑️ Correct signature for Ipv4Address & Ipv6Address

- zbus/Cargo.toml
- zbus/src/address.rs
- zbus/src/object_server.rs
A recursive depth-first search can be implemented using a deque.
> ➖ zbus: use less `async-recursion`

- Cargo.toml
- zbus/Cargo.toml
- zbus_macros/Cargo.toml
- zbus_names/Cargo.toml
- zbus_polkit/Cargo.toml
- zbus_polkit/src/policykit1.rs
- zbus_xmlgen/Cargo.toml
- zvariant/Cargo.toml
- zvariant_derive/Cargo.toml
- zvariant_utils/Cargo.toml
> 🔖 zv,zd,zb,zm: Bump major versions

- zbus/Cargo.toml
- zbus_names/Cargo.toml
- zbus_xmlgen/Cargo.toml
> 🔖 zx,zn: Bump major version

- .github/workflows/rust.yml
- zbus/src/lib.rs
- zbus/src/proxy/mod.rs
> 💚 CI: Always build and isntall pkg-config and cachine pkg-config files on Windows runner

- CONTRIBUTING.md
> 📝 CONTRIBUTING: Drop inexistent gitmoji blog post link

- book/src/client.md
- zbus_macros/src/lib.rs
- zbus_macros/src/proxy.rs
- zbus_macros/tests/tests.rs
- zbus_xmlgen/src/main.rs
> A fix & an API change to dbus_proxy

- zbus/src/blocking/proxy/builder.rs
- zbus/src/blocking/proxy/mod.rs
- zbus/src/proxy/builder.rs
- zbus/src/proxy/mod.rs
- zbus_macros/src/proxy.rs
> Streamline & simplify proxy::ProxyDefault and proxy building patterns/API

- zbus_xmlgen/src/main.rs
> 💄 zx: support --help and -h

- zbus/src/connection/handshake.rs
If the client asks for fd-passing on socket type that doesn't support it, reject the request.
---
> 🩹 zb: Server connection should reject fd-passing if not possible

- zbus_macros/src/iface.rs
> 🐛 zm: Handle `cfg` attributes in `dbus_interface` methods

- zbus/src/blocking/connection/mod.rs
- zbus/src/connection/mod.rs
- zbus/src/fdo.rs
- zbus/src/lib.rs
- zbus/src/message/builder.rs
- zbus/src/message/header.rs
- zbus/src/message/mod.rs
- zbus/tests/e2e.rs
- zbus_macros/src/iface.rs
> 🚸 zb: `Message` now immutable

- zbus/src/object_server/mod.rs
- zbus/tests/e2e.rs
The previous implementation is just incomplete and would cause all child nodes to be concated one by one instead of being enclosed.
Also updated the e2e tests to test this case.
Fixes 916b4cce00a0b85cb6e9a19695f9f1387832682e
---
**The bug** introduced by 916b4cce00a0b85cb6e9a19695f9f1387832682e
```
$ busctl introspect --user com.example.Service /
Invalid introspection data: duplicate method 'Get' on interface 'org.freedesktop.DBus.Properties'.
$ busctl tree --user com.example.Service
Failed to introspect object /example of service com.example.Service: Unknown object '/example'
Failed to introspect object /Service of service com.example.Service: Unknown object '/Service'
Failed to introspect object /com/Service of service com.example.Service: Unknown object '/com/Service'
└─ /com
└─ …
```
> 🐛 zb: use the correct traversal order for node tree introspection

- .github/workflows/rust.yml
- zbus_macros/src/iface.rs
- zvariant/src/serialized/data.rs
- zvariant/src/serialized/size.rs
- zvariant/src/serialized/written.rs
Hopefully this finally fixes the Windows CI being unable to download `pkg-config`.
Fixes #441.
> 💚 CI: Install pkg-config from tpm's repo on Windows

- zvariant/src/optional.rs
While we implement `NoneValue` for all `Default` types for convenience (both ours and users), we don't want to do that for `bool` because there is no way to distinguish between `None` and `false` in that case.
So let's panic on that and document this behavior.
> 🔥 zb: Panic on `Optional<bool>` type

- .github/workflows/rust.yml
- zbus/Cargo.toml
- zbus/src/connection/builder.rs
- zbus/src/fdo.rs
- zbus/src/object_server/mod.rs
- zbus_macros/Cargo.toml
- zbus_names/Cargo.toml
- zbus_xml/Cargo.toml
- zbus_xmlgen/Cargo.toml
- zvariant/Cargo.toml
- zvariant_derive/Cargo.toml
- zvariant_utils/Cargo.toml
This is not allowed and the bus disconnects us immediately.
> 🚑️ zb: Don't send ObjectManager signals before Hello method

- zbus/src/win32.rs
- Use `ptr.cast()` to convert type keeping `const`ness, instead of `as`
- Use `ptr::addr_of_mut!()` to get mut pointer, intead of `&mut`
> ♻️ zb/win32: Refactor raw pointer handling

- zbus/src/address/mod.rs
- zbus/src/address/transport/launchd.rs
- zbus/src/address/transport/mod.rs
- zbus/src/address/transport/unix.rs
- zbus/src/blocking/connection/builder.rs
- zbus/src/blocking/mod.rs
- zbus/src/connection/builder.rs
- zbus/src/lib.rs
- zbus/src/message/builder.rs
- zbus/src/message/mod.rs
- zbus_macros/src/proxy.rs
- zvariant/src/serialized/written.rs
Came up with these while porting `busd` to the new API.
> A few fixes and improvements

- .github/workflows/rust.yml
- zbus/src/address/transport/mod.rs
- zbus/src/address/transport/unix.rs
- zbus/src/connection/socket/unix.rs
- zbus/src/win32.rs
Currently Windows [test run passes even if cargo test fails](https://github.com/dbus2/zbus/actions/runs/7846283607/job/21412630240#step:12:381). This PR is an attempt to fix that and maybe [other issues that don't hit zbus' CI](https://github.com/dbus2/busd/actions/runs/7846368865/job/21412903360?pr=37#step:5:220) for some reason.
> Fix Windows CI

- zbus/src/connection/mod.rs
- zbus/src/match_rule/mod.rs
- zbus_macros/src/utils.rs
- zbus_xmlgen/src/lib.rs
- zbus_xmlgen/src/main.rs
- zvariant/src/fd.rs
> Fix a bunch of new clippy warnings

- zbus/src/win32.rs
Details at: https://github.com/microsoft/windows-rs/issues/2842
> 🚑️ zb: Fix a pointer access on Windows

- zbus/src/win32.rs
Based on suggestion from @nerix:
https://github.com/dbus2/zbus/pull/586#pullrequestreview-1874994014
> 🎨 zb,internal: Improve slice handling in win32 code

- Cargo.lock
- zbus/Cargo.toml
- zbus_macros/Cargo.toml
- zvariant/Cargo.toml
- zvariant_derive/Cargo.toml
This turned out to be [a bad idea](https://github.com/dbus2/zbus/issues/652#issuecomment-1962630425).
> Releases for reverting unpinning of zvariant_utils

- zbus/src/blocking/connection/builder.rs
- zbus/src/connection/builder.rs
- zbus/src/connection/mod.rs
- zbus/src/connection/socket/channel.rs
- zbus/src/connection/socket/mod.rs
- zbus/src/connection/socket_reader.rs
> ✨ zb: Allow high-level Socket impl + add in-process channel-based Connection support

- Cargo.lock
- zbus_macros/Cargo.toml
- zbus_macros/src/iface.rs
- zbus_macros/src/lib.rs
- zbus_macros/src/proxy.rs
- zbus_macros/src/utils.rs
- zvariant_derive/Cargo.toml
- zvariant_derive/src/dict.rs
- zvariant_derive/src/type.rs
- zvariant_derive/src/value.rs
- zvariant_utils/Cargo.toml
- zvariant_utils/src/macros.rs
Built on top of and replaces #404.
Fixes #401.
> ⬆️ zm,zv,zu: Update syn to v2.0.64

- zbus/src/connection/socket/mod.rs
I forgot to pass `-a` flag to `git commit` in the previous commit. :(
> 🚑️ Forgotten changes from commit 021a854425

- zbus/src/fdo.rs
- zbus_macros/src/iface.rs
- zvariant/src/lib.rs
- zvariant/src/ser.rs
- zvariant/src/utils.rs
This fixes and improves on #838.
> A few fixes & enhancements to proxy generation of interface macro

- Cargo.lock
- zbus/Cargo.toml
- zbus/src/connection/socket/unix.rs
> ⬆️ : Bump nix to v0.29

- README.md
- zbus/README.md
This should have been part of 9e443e32.
> 📝 README: "server" -> "service"

- zbus/src/connection/mod.rs
When registering a name, zbus will deadlock if it receives many messages before the RequestName reply. This occurs because:
1. The RequestName() call means the dbus server can send messages for that name _before_ it sends the RequestName() reply.
2. While name registration is in progress the registered names lock is held.
3. These messages are queued on a sender channel.
4. The queued messages are not dispatched because the object server task blocks waiting for the registered names lock (see 2 above).
5. This sender channel can become full, blocking the receiver task when it attempts to enqueue on a full channel.
6. If the receiver task blocks it does not receive the RequestName() reply and name registration.
7. Since name registration never completes the registered names lock is never …
> 🐛 zbus: Fix deadlock during name registration

- Cargo.lock
- zbus/Cargo.toml
- zvariant/Cargo.toml
- zvariant/src/lib.rs
- zvariant/src/type.rs
heapless is now an optional dep in zvariant and zbus.
> ✨ zv,zb: Add Type impl for heapless::{String, Vec}

- zbus/src/object_server/mod.rs
- zbus/tests/e2e.rs
> 🚑️ zb: Handle non-existent method calls correctly

- book/src/client.md
- book/src/concepts.md
- book/src/connection.md
- Update dead notification spec links
- Update obsolete systemd refs links
> 📝 book: update dead and obsolete fd.o links

- zvariant/src/lib.rs
- zvariant/src/parsed/signature.rs
> Forgotten changes from PR #966

- zbus/src/object_server/dispatch_notifier.rs
- zbus/src/object_server/interface/dispatch_result.rs
- zbus/src/object_server/interface/interface_deref.rs
- zbus/src/object_server/interface/interface_ref.rs
- zbus/src/object_server/interface/mod.rs
- zbus/src/object_server/mod.rs
- zbus/src/object_server/node.rs
Mostly just splitting each type into its own module and file.
> ♻️  zb: object_server module refactoring

- Cargo.lock
- zbus/Cargo.toml
- zbus/src/connection/mod.rs
- zbus/src/connection/socket/vsock.rs
> ⬆️  zb: Upgrade to tokio-vsock 5

- zbus/Cargo.toml
- zbus_macros/Cargo.toml
- zbus_macros/tests/tests.rs
- zbus_names/Cargo.toml
- zbus_xml/Cargo.toml
- zbus_xmlgen/Cargo.toml
- zvariant/Cargo.toml
- zvariant/src/ser.rs
- zvariant_derive/Cargo.toml
- zvariant_utils/Cargo.toml
We don't really need to currently but it's a good idea to do this in a major version bump.
> ⬆️  all: Bump MSRV

- .github/workflows/rust.yml
- Cargo.lock
- zbus/src/proxy/builder.rs
- zbus_macros/Cargo.toml
- zbus_macros/src/iface.rs
- zbus_macros/src/proxy.rs
> 🦺 zm: Verify user supplied strings at compile time

- .github/renovate.json
> 🤖 renovate: Attempt to fix PR titles & mark micro updates as such

- Cargo.toml
- zbus/Cargo.toml
- zbus_macros/Cargo.toml
- zbus_names/Cargo.toml
- zbus_xml/Cargo.toml
- zbus_xmlgen/Cargo.toml
- zvariant/Cargo.toml
- zvariant_derive/Cargo.toml
- zvariant_utils/Cargo.toml
> ♻️  all: Inherit common Cargo.toml props from the workspace

- zvariant_derive/src/value.rs
- zvariant_derive/tests/tests.rs
> ✨ zv: *Value derive now supports optional fields in dict structs

- zbus/src/address/transport/mod.rs
- zvariant/src/array.rs
> 🎨 Clippy fixes

- Cargo.lock
- zbus/Cargo.toml
> ➖ zb: Drop uneeded deps xdg-home & async-fs

- zbus_macros/src/iface.rs
> 🐛 zm: Disambiguate the Interface method arguments

- zbus/src/proxy/mod.rs
NameOwnerChangedStream is *already* ordered, so switching out the .map implementation and implementing OrderedStream is all that's needed.
> ✨ zb: Make OwnerChangedStream ordered

- zvariant/src/lib.rs
- zvariant/src/type/libstd.rs
> 🚑️ Ensure empty array is (de)serialized the same way as unit type

- zbus/Cargo.toml
- zbus_macros/Cargo.toml
- zbus_names/Cargo.toml
- zbus_xml/Cargo.toml
- zbus_xmlgen/Cargo.toml
- zvariant/Cargo.toml
- zvariant_derive/Cargo.toml
This implicity bumps the local deps everywhere to the latest.
> 🩹 all: Don't use workspace for local deps

- Cargo.lock
- zbus/src/message/mod.rs
- zvariant/Cargo.toml
- zvariant/src/as_value/deserialize.rs
- zvariant/src/as_value/serialize.rs
- zvariant/src/lib.rs
- zvariant_derive/Cargo.toml
>  🔖 zv,zd: Release 5.5.1

- Cargo.lock
- zbus/Cargo.toml
- zbus_macros/Cargo.toml
> 🔖 zb,zm: Release 5.6.0

- zvariant/tests/dict_value.rs
- zvariant_derive/src/dict.rs
> 🚑️ zd: Fix use of empty structs with SerializeDict

- Cargo.lock
- zvariant/Cargo.toml
- zvariant_derive/Cargo.toml
> 🔖 zv,zd: Release 5.5.3

- zbus/src/win32.rs
- zvariant/src/utils.rs
- zvariant/tests/common.rs
- zvariant/tests/number/f64_value.rs
- zvariant/tests/number/mod.rs
Also fix a regression from 48d397c0.
> 🚨 zv,zb: Fixes against latest clippy

- Cargo.lock
- zbus/Cargo.toml
- zbus_macros/Cargo.toml
> 🔖 zb,zm: Release 5.8.0

- zbus_xmlgen/src/main.rs
> 🎨 zx: Satisfy latest clippy

- Cargo.lock
- zbus/Cargo.toml
- zbus/src/abstractions/timeout.rs
- zbus/tests/e2e.rs
- zbus_macros/Cargo.toml
- **♻️  zb: Micro simplification**
- **🔖 zb,zm: Release 5.11.0**
> 🔖 zb,zm: Release 5.11.0

- book/src/blocking.md
- book/src/client.md
- book/src/service.md
People might want to skip to specific chapter, only c&p the code in that section and expect it to work out of the box but it won't because they'll be missing imports and end up figuring that out.
> 📝 book: Don't hide imports

- zbus/src/connection/mod.rs
Replaced `info_span!("{}", task_name)` with descriptive span names and structured fields. Spans now have meaningful static names like `monitor_name_lost`, and `monitor_name_acquired` with `name = %well_known_name`.
The issue is that `info_span!("{}", task_name)` doesn't work like a format string. In tracing, the first argument to info_span! is always the literal span name, not a format string.
**Output before this PR:**
2025-09-16T14:19:15.862Z  INFO {}{task_name="monitor name org.example.Service acquired"}: zbus::connection: Processing connection in task
2025-09-16T14:19:15.862Z  INFO {}: Processing connection in task
2025-09-16T14:19:15.862Z  INFO {}: Handling lost connection
**Output after this PR:**
2025-09-16T14:23:19.341Z  INFO monitor_name_acquired{name=org.example.Service}: …
> 🐛 zb: Fix tracing span names showing as "{}"

- .github/workflows/rust.yml
The codegen test needs rustfmt.
> 💚 Explicitly install rustfmt component for test jobs
